#!/usr/bin/env python3
# © 2026 aiaiaiai · aiaiaiai.org
# SPDX-License-Identifier: Apache-2.0
"""Build the prism-signal-observe gazetteer from a GeoNames country dump.

Usage:
    python3 scripts/build-geonames-gazetteer.py UA.zip > crates/prism-signal-observe/data/gazetteer-ua.tsv

Input is https://download.geonames.org/export/dump/UA.zip (or the extracted UA.txt).
GeoNames data is licensed CC BY 4.0; the output keeps that attribution in its header.

Kept: populated places (feature class P) with a population of at least MIN_POPULATION,
plus every national, regional, and district seat whatever its population. City sections
(PPLX) and historical or abandoned places are left out. Aliases are the
Cyrillic alternate names and the ASCII name. Output is sorted by GeoNames id, so the same
input always gives the same bytes.
"""

import io
import re
import sys
import unicodedata
import zipfile

MIN_POPULATION = 1000
SEAT_CODES = {"PPLC", "PPLA", "PPLA2"}
# Sections of a city (PPLX) and historical or abandoned places are left out: a city
# district's population would outweigh the village that shares its name.
EXCLUDED_CODES = {"PPLX", "PPLH", "PPLQ", "PPLW"}
CYRILLIC = re.compile(r"[Ѐ-ӿ]")
UNSAFE = re.compile(r"[\t,\r\n]")


def read_rows(path):
    if path.endswith(".zip"):
        with zipfile.ZipFile(path) as archive:
            member = next(n for n in archive.namelist() if n.endswith(".txt") and "readme" not in n.lower())
            data = archive.read(member).decode("utf-8")
    else:
        with open(path, encoding="utf-8") as handle:
            data = handle.read()
    for line in io.StringIO(data):
        fields = line.rstrip("\n").split("\t")
        if len(fields) >= 19:
            yield fields


def strip_stress(text):
    """Removes combining marks such as the stress accent in "Ові́діополь"."""
    decomposed = unicodedata.normalize("NFD", text)
    kept = "".join(c for c in decomposed if not unicodedata.combining(c) or c in "\u0306\u0308")
    return unicodedata.normalize("NFC", kept)


def aliases(name, asciiname, alternates):
    seen = {name}
    out = []
    for candidate in [asciiname, *alternates.split(",")]:
        candidate = strip_stress(candidate.strip())
        if not candidate or candidate in seen or UNSAFE.search(candidate):
            continue
        if candidate != asciiname and not CYRILLIC.search(candidate):
            continue
        seen.add(candidate)
        out.append(candidate)
    return sorted(out)


def main(argv):
    if len(argv) != 2:
        sys.exit(__doc__)
    places = []
    modified = ""
    for f in read_rows(argv[1]):
        geonameid, name, asciiname, alternates = f[0], f[1], f[2], f[3]
        lat, lon, feature_class, feature_code = f[4], f[5], f[6], f[7]
        population = int(f[14] or 0)
        if feature_class != "P" or feature_code in EXCLUDED_CODES:
            continue
        if population < MIN_POPULATION and feature_code not in SEAT_CODES:
            continue
        if UNSAFE.search(name):
            continue
        modified = max(modified, f[18])
        places.append(
            (
                int(geonameid),
                name,
                lat,
                lon,
                feature_code,
                population,
                ",".join(aliases(name, asciiname, alternates)),
            )
        )
    places.sort()
    out = sys.stdout
    out.write("# Gazetteer for prism-signal-observe, generated by scripts/build-geonames-gazetteer.py.\n")
    out.write("# Source: GeoNames (https://www.geonames.org), licensed CC BY 4.0.\n")
    out.write(f"# Newest source record: {modified or 'unknown'}. Places: {len(places)}.\n")
    out.write("# id\tname\tlat\tlon\tfeature\tpopulation\taliases\n")
    for geonameid, name, lat, lon, code, population, alias_list in places:
        out.write(f"geonames:{geonameid}\t{name}\t{lat}\t{lon}\t{code}\t{population}\t{alias_list}\n")


if __name__ == "__main__":
    main(sys.argv)
